services:
  postgres:
    extends:
      file: ./apps/backend/docker-compose.yml
      service: postgres

networks:
  backend:
    driver: bridge

volumes:
  db:
    # Optionally, you can specify driver or additional configuration here if needed.
