version: "3.8"
services:
  postgres:
    image: postgres:15.7
    ports:
      - "5433:5432"
    container_name: monex-p-db
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monex-p-db

volumes:
  db:
  cache:
