version: "3.8"
services:
  postgres:
    image: postgres:15.7
    ports:
      - "5432:5432"
    container_name: web-payload
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: web-payload

volumes:
  db:
  cache:
